services:
  db:
    image: postgres:14.13
    container_name: test_privatbank-db-1
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: test_privatbank-backend-1
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: test_privatbank-frontend-1
    env_file:
      - .env
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  db_data:
